[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib", "test", "scripts", "examples", "deploy"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solmate/=lib/solmate/src/",
    "univ3-core/=lib/v3-core/contracts/",
    "univ3-periphery/=lib/v3-periphery/contracts/",
    "@contracts/=contracts/",
    "@univ3-libraries/=contracts/univ3-libraries/",
    "@libraries/=contracts/libraries/",
    "@multicall/=contracts/multicall/",
    "@periphery/=contracts/periphery/",
    "@tokens/=contracts/tokens/",
    "@types/=contracts/types/",
    "@scripts/=scripts/",
    "@uniswap/=lib/",
]
optimizer = {enabled = true, runs = 200}
